### ISSUE TITLE
DESeq has been deprecated

### ISSUE THREAD

**Issue by hamid-bolouri** [heiniglab/scPower#1]
Hi; 

It looks like scPower requires DESeq, which has been deprecated (replaced by DESq2) and is not available for R 4.0. Is there a work-around to allow scPower installation and use (in my case on Ubuntu)?

Thanks,

Hamid

**Comment by KatharinaSchmid** [comment]
Hi Hamid,

thanks for your interest in our tool and sorry for the late response. We had some issues when using DESeq2 on single cell data (because of too long runtime) and therefore stayed with DESeq at the moment. But you aright that it is an outdated tool and I will work on replacing it. 

In the meantime it is probably faster if you would manage to install DESeq. I was able to install it for R 4.0.2 under Fedora. Can you tell me what exact R version you are using and what your error message is?

Regards,
Katharina

**Comment by hamid-bolouri** [comment]
Thanks for getting back to me Katharina. How did  you install DESeq? It fails for me. Details below.

My R version is:

R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

Using

> BiocManager::install("DESeq")

gives:

Warning messages:
1: package ‘DESeq’ is not available for this version of R

I did some Googling and based on past Bioc Support posts, I removed and reinstalled my BiocManager (and BiocVersion) with no effect. I also tried:

> install.packages("DESeq",
+  repos=c('http://bioconductor.org/packages/release/bioc/',
+ 'http://cran.wustl.edu/',
+ 'http://bioconductor.org/packages/release/data/annotation'),
+ dependencies=TRUE, INSTALL_opts = c('--no-lock'))

Again, I got:

Warning message:
package ‘DESeq’ is not available for this version of R

DESeq2 installed without any problems. So the issue seems to be specific to the old version of DESeq.

Thanks

Hamid

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3

**Comment by KatharinaSchmid** [comment]
Thanks for the detailed output. The problem seems to be the newest Bioconductor release 3.12 from end of October (I set up my R4.0.2 environment before). A quick fix for now would be installing DESeq from the previous Bioconductor release. What worked for me (also with R4.0.3) was:

```
BiocManager::install(version="3.11")
BiocManager::install("DESeq")
```

I hope this is helpful for the moment. Sorry for the inconvenience. And thanks again for reporting the problem, I am working on removing the DESeq dependency and can hopefully soon push a stable version.

**Comment by hamid-bolouri** [comment]
Thanks for the suggestion Katharina. Unfortunately, if I do

`BiocManager::install(version="3.11")`

I get a warning:

`Downgrade 65 packages to Bioconductor version '3.11'? [y/n]:`

which seems risky! So I think I will just have to wait till DESeq2 becomes compatible or unnecessary in scPower!  Thanks again.  --Hamid

**Comment by KatharinaSchmid** [comment]
Hi Hamid, I removed the dependency to DESeq, you should be able to install scPower now also for R4. Please come back to me if you have any further problems or questions. Thanks for reporting your issue!

**Comment by hamid-bolouri** [comment]
Yay! That is great. Thank you very much Katharina, both for resolving the issue quickly, and also for an excellent package!
